### ISSUE TITLE
Stress/Strain Viewer 1D plot don't work on analysis

### ISSUE THREAD

**Issue by rosswhitfield** [neutrons/PyRS#640]
This works on Ubuntu 20.04 with matplotlib 3.1.2 but fails on analysis with matplotlib 2.2.3 with
```
Traceback (most recent call last):
  File "/SNS/software/PyRS/build/lib/pyrs/interface/strainstressviewer/strain_stress_view.py", line 499, in updatePropertyFromModel
    getattr(self, name)(getattr(self.model, name))
  File "/SNS/software/PyRS/build/lib/pyrs/interface/strainstressviewer/strain_stress_view.py", line 509, in selectedPeak
    self.update_plot()
  File "/SNS/software/PyRS/build/lib/pyrs/interface/strainstressviewer/strain_stress_view.py", line 493, in update_plot
    stress_case=self.stressCase.get_stress_case()))
  File "/SNS/software/PyRS/build/lib/pyrs/interface/strainstressviewer/strain_stress_view.py", line 371, in set_ws
    ax.errorbar(getattr(field, scan_dir), field.values, field.errors, marker='o')
AttributeError: 'NoneType' object has no attribute 'errorbar'
/SNS/software/PyRS/pyrs.sh: line 13: 189183 Aborted                 (core dumped) QT_API=pyqt5 PYTHONPATH=$DIREC/build/lib $MANTIDPYTHON --classic $DIREC/build/scripts-3.6/pyrsplot
```
